name: slicer-install-extensions
author: Sebastien Goll (Kitware SAS)
description: Install extensions for Slicer

inputs:
  slicer_exe:
    description: Slicer executable
    required: true
  additional_arguments:
    description: Additional arguments for Slicer executable
    default: '--no-main-window --no-splash'
  extensions_name:
    description: Extensions names to install
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/slicer-run-python-script
      with:
        script: ${{ github.action_path }}/install_extensions.py
        slicer_exe: ${{ inputs.slicer_exe }}
        additional_arguments: ${{ inputs.additional_arguments }} ${{ inputs.extensions_name }}
